version: '2'

services:
  web:
    # restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/static
    # 2 ways of running Django server: Gunicorn or Python built-in server.
    # They are mutually exclusive.
    #
    # Detect code changes automatically and reload Gunicorn
    # Debugging with Gunicorn is a bit hard according to this posts
    # http://stackoverflow.com/questions/8950674/debugging-a-flask-app-running-in-gunicorn
    # wsgi.py file is located in the directory of the project.
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project.wsgi:application --reload
    #
    # Use Python's built-in webserver instead of Gunicorn.
    #command: python manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
    - web