version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    # Required to connect to MySQL service from localhost, or host machine.
    # Port is required, as EXPOSE command in mysql image only indicates
    # that MySQL container is listening on the port. Onle listing the ports
    # makes them accessible from the outside.
    ports:
      - 9090:3306
    # Pass in extra parameters to starting mysql to modify
    # the default collation and character set
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: django
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password

  web:
    # restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web:/usr/src/app
    # 2 ways of running Django server: Gunicorn or Python built-in server.
    # They are mutually exclusive.
    #
    # Detect code changes automatically and reload Gunicorn
    # Debugging with Gunicorn is a bit hard according to this posts
    # http://stackoverflow.com/questions/8950674/debugging-a-flask-app-running-in-gunicorn
    # wsgi.py file is located in the directory of the project.
    command: /usr/local/bin/gunicorn -w 2 -b :8000 project.wsgi:application --reload
    #
    # Use Python's built-in webserver instead of Gunicorn.
    #command: python manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
      - web

# Volume definitions
volumes:
  db:


#  # Requires modification on default Docker host on OSX.
#  # @see https://github.com/docker-library/elasticsearch/issues/133#issuecomment-257459826
#  elasticsearch:
#    image: elasticsearch
#    ports:
#      - 9200:9200
#      - 9300:9300
#    security_opt:
#      - label:seccomp:unconfined
#    command: elasticsearch -Etransport.host=0.0.0.0 -Ediscovery.zen.minimum_master_nodes=1
#    environment:
#      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
#
#  kibana:
#    image: kibana:5
#    restart: unless-stopped
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#
#  logstash:
#    image: logstash
#    command: logstash -e 'input { tcp { port => 5000 } } output { elasticsearch { hosts => "elasticsearch:9200" } }'
#    ports:
#      - "5000:5000"
#      # Beats input -- https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-beats.html
#      - '5044:5044'
#      # UDP input -- https://www.elastic.co/guide/en/logstash/master/plugins-inputs-udp.html#plugins-inputs-udp-codec
#      - '43448:43448/udp'
#      # Monitoring APIs -- https://www.elastic.co/guide/en/logstash/5.0/monitoring.html
#      - '9600:9600'
#    depends_on:
#      - elasticsearch
