# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
