# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
            ],
            options={
                'ordering': ['first_name'],
                'proxy': True,
                'indexes': [],
            },
            bases=('topics.person',),
        ),
    ]
