version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    # Pass in extra parameters to starting mysql to modify
    # the default collation and character set
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: m39cisk3T
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: glx94Wrk

  nginx:
    image: haagendazs/drupal-nginx:2
    restart: always
    volumes_from:
      - php
    ports:
      - 8000:80

  php:
    image: haagendazs/drupal-php:2
    restart: always
    volumes:
      - ./:/var/www/html
      - files:/var/www/html/files

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8001:80
    volumes:
      - /sessions

# Volume definitions
volumes:
  db:
  files:
