version: '2'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/project/static
    # Detect code changes automatically and reload Gunicorn
    command: /usr/local/bin/gunicorn -w 2 -b :8000 wsgi:app --reload

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    depends_on:
    - web