version: '2'
services:
  web:
    build: .
    ports:
    - "80:5000"
    volumes:
    - .:/code
    depends_on:
    - redis
    environment:
      FLASK_APP: flaskr
      FLASK_DEBUG: "true"
    # Without specifying the host, the internal flask server runs on port 127.0.0.1.
    # This means the server is only accessible from the container itself. Specifying
    # the port as 0.0.0.0 allows connections from anywhere, including the Docker host.
    command: flask run --host=0.0.0.0
  redis:
    image: redis