 version: '2'
 services:
   nginx:
      build: ./nginx
      ports:
        - "8000:8000"
      volumes:
        - ./src/composeexample/static:/static
        - ./src/elasticsearchpoc/static:/static
      depends_on:
        - web 
   db:
     image: postgres

   web:
     restart: always
     build: .
     volumes:
       - ./src:/code
       - ./src/composeexample/static:/static
       - ./src/elasticsearchpoc/static:/static
     command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn composeexample.wsgi -b 0.0.0.0:8000 --reload"
     expose: 
      - "8000"
     depends_on:
       - db

   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
     ports:
      - 9200:9200
      - 9300:9300
     security_opt:
      - label:seccomp:unconfined
     volumes:
      - ./config/elastic_search:/config
     command: elasticsearch -Etransport.host=0.0.0.0 -Ediscovery.zen.minimum_master_nodes=1 -Edefault.path.repo=/config/backups -Expack.security.enabled=false
     environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

   kibana:
    image: kibana:5
    restart: unless-stopped
    ports:
      - "5601:5601"


