 version: '2'
 services:
   db:
     image: postgres
   web:
     build: .
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - ./src:/code
     expose: 
      - "8000"
     ports:
       - "8000:8000"
     depends_on:
       - db
   elasticsearch:
     image: elasticsearch
     ports:
      - 9200:9200
      - 9300:9300
     security_opt:
      - label:seccomp:unconfined
     command: elasticsearch -Etransport.host=0.0.0.0 -Ediscovery.zen.minimum_master_nodes=1
     environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
   kibana:
    image: kibana:5
    restart: unless-stopped
    ports:
      - "5601:5601"
